apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-backup-pvc
  namespace: couchdb
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: portworx-shared-sc
  volumeMode: Filesystem
