name: Build and Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to RedHat Registry
      run: echo ${{ secrets.REDHAT_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REDHAT_REGISTRY_USERNAME }} --password-stdin
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: byroncollins/couchbackup
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}