name: Build and Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: redhat registry login
      run: echo "${{ secrets.REDHAT_REGISTRY_PASSWORD }}" | docker login registry.redhat.io -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: byroncollins/couchbackup
        tag_with_ref: true
