name: Build and Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: redhat registry login
      run: echo "${{ secrets.REDHAT_REGISTRY_PASSWORD }}" | docker login registry.redhat.io -u "${{ secrets.REDHAT_REGISTRY_USERNAME }}" --password-stdin
    - name: pull base image
      run: docker pull registry.redhat.io/ubi8/nodejs-12

    - name: Build and push Docker redhat ubi images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: byroncollins/couchbackup
        tags: nodejs-12-ubi
        tag_with_ref: true
        cache_froms: registry.redhat.io/ubi8/nodejs-12

    - name: Build and push Docker alpine images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: byroncollins/couchbackup
        tags: nodejs-12-alpine
        tag_with_ref: true
        cache_froms: node:12-alpine