name: Build and Publish Docker
on: [push]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        baseimage:
          - { image: "registry.redhat.io/ubi8/nodejs-12", tag:  nodejs-12-ubi, dockerfile: Dockerfile.ubi }
          - { image: "node:12-alpine", tag: nodejs-12-alpine, dockerfile: Dockerfile.alpine }
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: redhat registry login
      run: echo "${{ secrets.REDHAT_REGISTRY_PASSWORD }}" | docker login registry.redhat.io -u "${{ secrets.REDHAT_REGISTRY_USERNAME }}" --password-stdin
    - name: pull base ubi images
      run: docker pull registry.redhat.io/ubi8/nodejs-12

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        build_args: BASEIMAGE=${{ matrix.baseimage.image }}
        dockerfile: ${{ matrix.baseimage.dockerfile }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: byroncollins/couchbackup
        tags: ${{ matrix.baseimage.tag }}
        cache_froms: registry.redhat.io/ubi8/nodejs-12